version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: GO111MODULE=off go get github.com/onsi/ginkgo/ginkgo
      - run: ginkgo -r -v --randomizeAllSpecs --randomizeSuites --trace --progress --race
