name: Release Checker
on:
  pull_request:
    paths: [ 'version.json' ]
    branches: [ master ]

jobs:
  releaser:
    runs-on: ubuntu-latest
    env:
      HIGHESTRELEASED: ""
      VERSION: ""
      GORELEASE: ""
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.x"
      - name: Install gorelease
        run: go install golang.org/x/exp/cmd/gorelease@v0.0.0-20210729172720-737cce5152fc
      - name: Determine version
        run: echo "VERSION=$(jq -r .version version.json)" >> $GITHUB_ENV
      - name: Determine highest released version
        run: echo "HIGHESTRELEASED=$(go list -m -versions | tr " " "\n" | tail -n 1)" >> $GITHUB_ENV
      - name: Run gorelease
        id: gorelease
        if: env.VERSION != env.HIGHESTRELEASED
        run: |
          output=$(gorelease || true)
          # dealing with multi-line strings in GitHub Actions is a pain
          echo "GORELEASE<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - uses: marocchino/sticky-pull-request-comment@v2
        if: env.VERSION != env.HIGHESTRELEASED
        with:
          header: test
          recreate: true
          message: |
            Most recent release is: ${{ env.HIGHESTRELEASED }}

            `gorelease` says:
            ```
            ${{ env.GORELEASE }}
            ```
