on: [push, pull_request]

jobs:
  unit:
    strategy:
      matrix:
        os: [ "ubuntu", "windows", "macos" ]
        go: [ "1.15.x", "1.16.x" ]
    runs-on: ${{ matrix.os }}-latest
    name: Unit tests (${{ matrix.os}}, Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: ${{ matrix.go }}
      - run: go version
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/ginkgo
      - name: Install dependencies
        run: go install
      - name: Run tests
        env:
          QLOGDIR: "qlog"
        run: ginkgo -r -v --cover -coverprofile coverage.txt --randomizeAllSpecs --randomizeSuites --trace --progress
      - name: Run tests (32 bit)
        if: ${{ matrix.os != 'macos' }} # can't run 32 bit tests on OSX.
        env:
          GOARCH: 386
          QLOGDIR: "qlog"
        run: ginkgo -r -v -outputdir . -randomizeAllSpecs -randomizeSuites -trace -skipPackage integrationtests,benchmark
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: qlog
          path: qlog/
